version = 0.1

[default.global.parameters]
stack_name = "anonymous-chat"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "anonymous-chat"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
disable_rollback = false
